import './globals.css'
import type { Metadata } from 'next'
 

 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="icon" href="/favicon.png" sizes="any" />
       <link href="https://api.fontshare.com/v2/css?f[]=satoshi@900,700,500,300,400&display=swap"
      rel="stylesheet"
    />
    </head>
      <body className=''><div id="root" className='overflow-hidden'>{children}</div></body>
    </html>
  )
}
 
   
    